import {StyleSheet} from 'react-native'
import { COLORS, FONTS, SIZES } from "../../components/theme";

const Styles = StyleSheet.create({
  containerfull:{
    backgroundColor:COLORS.green,
    width:'100%',
    height:'100%',    
  },
  main_header_text:{
    fontSize:24,
    fontFamily:FONTS.NanumSquareEB,
    color:"#ffffff",
    marginTop:50,
    marginBottom:15,
    marginLeft:44,
  },
  main_whitecontainer:{
    flex:5,
    //height:'60%',
    width:'100%',
    backgroundColor:COLORS.backgray,
    borderTopLeftRadius:40,
    borderTopRightRadius:40,  
  },
  main_whitecontainer_box:{    
    height:154,
    backgroundColor:COLORS.white,
    elevation:2,
    marginTop:40,
    marginHorizontal:40,
    borderRadius:20,
    padding:36,
  },
  main_whitecontainer_text:{
    fontSize:16,
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.gray,
  },
  main_whitecontainer_text2:{
    fontSize:16,
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.green,
    marginTop:12,
  },
  tabbar:{
    width:296,
    height:64,
    backgroundColor:COLORS.white,
    elevation:1,
    borderRadius:32,
    alignSelf:'center',
    position:'absolute',
    bottom:32,
    justifyContent:'space-around',
    display:'flex',
    flexDirection:'row',
    alignItems:'center'
  },
  tabbar_button:{
    width:70,
    height:70,
    borderRadius:35,
    backgroundColor:COLORS.green,
    alignSelf:'center',
    position:'absolute',
    elevation:2,
    bottom:48,
    alignItems:'center',
    justifyContent:'center'
  },
  main_category_text:{
    fontSize:20,
    fontFamily:FONTS.NanumSquareEB,
    color:COLORS.green,
    marginTop:28,
    marginLeft:40,
  },
  main_categorytext:{
    fontFamily:FONTS.NanumSquareEB,
    color:COLORS.white,
    fontSize:16,
  },
  main_categorycard:{
    backgroundColor: COLORS.green2, 
    marginTop:10,
    flex:1,
    width:140,
    borderRadius:20,
    marginRight:8,
    alignItems:'center',
    justifyContent:'center',    
  },
  whitecontainer:{
    marginTop:36,
    flex:1,
    width:'100%',
    backgroundColor:COLORS.backgray,
    borderTopLeftRadius:40,
    borderTopRightRadius:40,  
    padding:30,
  },
  header:{
    flexDirection:'row',
    alignItems:'center',
    marginBottom:32,
  },
  header_title:{
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.gray,
    fontSize:18,
  },
  header_text:{
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.green2,
    fontSize:20,
    textAlign:'center',
    marginBottom:12,
    lineHeight:30,
  },
  categorytext:{
    fontFamily:FONTS.NanumSquareEB,
    color:COLORS.gray,
    fontSize:18,
    marginLeft:20
  },
  categorycard:{
    backgroundColor: COLORS.white, 
    width:SIZES.width-96,
    height:56,
    alignSelf:'center',
    justifyContent:'center',
    borderRadius:15,
    marginBottom:14,
    elevation:1,    
  },
  category_list:{    
    justifyContent:'space-between',
    //height:154,
    backgroundColor:COLORS.white,
    paddingVertical:36,
    paddingHorizontal:28,
    borderRadius:20,
    elevation:1,
    marginBottom:24,
  },
  category_text1:{
    fontFamily:FONTS.NanumSquareEB,
    color:COLORS.black,
    fontSize:16,
    lineHeight:24,
  },
  category_text2:{
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.DarkGray,
    marginTop:24,
    fontSize:12,
  },
  play_list:{
    height:72,
    flexDirection:'row',
    justifyContent:'space-between',
    paddingHorizontal:10
  },
  play_list_ninametext:{
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.black,
    fontSize:20,
  },
  play_list_nicknametext2:{
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.lightGray,
    fontSize:18,
  },
  play_list_timetext:{

  },
  play_list_button_container:{
    width:60,
    flexDirection:'row',
    justifyContent:'space-between',
  },
  play_question_text:{
    fontFamily:FONTS.NanumSquareEB,
    color:COLORS.gray,
    fontSize:18,
    alignSelf:'center'
  },
  play_rando_container:{
    flex:6,
    backgroundColor:COLORS.skyblue,
    borderRadius:40,
    margin:20,
    justifyContent:'center',
    // alignItems:'center'
  },
  play_nickname_text:{
    fontFamily:FONTS.NanumSquareB,
    color:COLORS.gray,
    fontSize:18,
  },
  play_button_container:{
    flex:3,
    paddingHorizontal:20
  },

})

export default Styles;